# Â© 2024 Blaine Freestone, Carson Bush, Brent Nelson

# This file is part of the Maeser usage example.

# Maeser is free software: you can redistribute it and/or modify it under the terms of
# the GNU Lesser General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.

# Maeser is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License along with
# Maeser. If not, see <https://www.gnu.org/licenses/>.

### API keys are required for OpenAI and GitHub integrations ###

api_keys:
  openai_api_key: '...'
  github_client_secret: '...'


### Other application configurations ###

### Github Auth ###

github:
  github_client_id: '...'
  github_callback_uri: '...'
  timeout: 10

### LDAP3 Auth ###

ldap3:
  name: '...'
  ldap_server_urls: ['...', '...']
  ldap_base_dn: '...'
  attribute_name: '...'
  search_filter: '({attribute_name}={...})'
  object_class: '...'
  attributes: ['{attribute_name}', '...', '...']
  ca_cert_path: '...'
  connection_timeout: 10

rate_limit:
  max_requests_remaining: 5            # The maximum number of requests that a user can have at any given time
  rate_limit_interval_seconds: 180      # The time interval in seconds that the rate limit is enforced


### Configure the logging path, prompt path, and rate vectorstore options ###

logging:
  log_source_path: example/chat_logs
  

vectorstore:
  vec_store_path: example/vectorstores
  vec_store_type: faiss


### Configure the LLM and text embedding models ###

embed:
  embed_model: text-embedding-3-large
  embed_provider: openai

llm:
  llm_model_name: gpt-4o
  llm_provider: openai
  token_limit: 400


### Configure the user management ###

user_management:
  accounts_db_path: example/chat_logs/users.db
  chat_history_path: example/chat_logs